# Generated by Django 4.1.1 on 2022-09-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='age',
            field=models.IntegerField(null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.CharField(max_length=80, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='report',
            name='number_1',
            field=models.IntegerField(null=True, verbose_name='number_1'),
        ),
    ]
