# Generated by Django 4.1.1 on 2022-09-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_report_age_report_email_report_number_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.AlterField(
            model_name='report',
            name='id_code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='id_code'),
        ),
    ]
