# Generated by Django 4.1 on 2022-09-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0003_remove_report_id_alter_report_id_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='number_1'),
        ),
    ]
