# Generated by Django 4.1.1 on 2022-10-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0004_alter_report_age_alter_report_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='allergies_1',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='report',
            name='allergies_2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='report',
            name='allergies_3',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='report',
            name='direccion',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='report',
            name='email_2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='report',
            name='nss',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='report',
            name='number_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='number_1'),
        ),
        migrations.AddField(
            model_name='report',
            name='number_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='number_1'),
        ),
        migrations.AddField(
            model_name='report',
            name='number_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='number_1'),
        ),
    ]
