# Generated by Django 4.1.1 on 2022-10-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0005_report_allergies_1_report_allergies_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='curp',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Curp'),
        ),
        migrations.AlterField(
            model_name='report',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='report',
            name='allergies_1',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Alergia 1'),
        ),
        migrations.AlterField(
            model_name='report',
            name='allergies_2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Alergia 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='allergies_3',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Alergia 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='direccion',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='report',
            name='email_2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Correo electronico 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='report',
            name='nss',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='NSS'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero 1'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero 4'),
        ),
    ]
