# Generated by Django 4.1.1 on 2022-10-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0006_report_curp_alter_report_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='blood',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Tipo de sangre'),
        ),
        migrations.AlterField(
            model_name='report',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='report',
            name='email_2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Correo electrónico 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_1',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Numero 1'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_2',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Numero 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_3',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Numero 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_4',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Numero 4'),
        ),
    ]
